version: 2

sources:
  - name: public
    database: postgres
    schema: public
    tables:
      - name: dim_teams
      - name: dim_leagues
      - name: raw_games
      - name: raw_ufc
      - name: raw_f1
      - name: raw_npb
      - name: raw_eurobasket
      - name: raw_boxing