version: 2

sources:
  - name: external_data
    database: postgres
    schema: public
    tables:
      - name: raw_games
      - name: raw_ufc
      - name: raw_f1
      - name: raw_sumo
      - name: raw_npb
      - name: raw_eurobasket
      - name: raw_boxing